### ISSUE TITLE
Sphere::RandomPointOnSurface has a high rate of failure for smaller spheres

### ISSUE THREAD

**Issue by zao** [juj/MathGeoLib#40]
I noticed some serious startup delay in my code in debug mode and did some random breaks to see where the time was spent.
On the first try, I hit the "astronomically small probability" in `Sphere::RandomPointOnSurface`, which ends up constructing a rather expensive stack trace which ends up in the void as I have no console attached.

I enter this code via `float3::RandomDir(lcg, 0.1f)`, so `r` is `0.1`. This means that the `lenSq < r*r` is going to be way less likely in my test case than for the unit sphere.
Doing some highly unscientific sampling, I end up at around 700-900 iterations when succeeding, and most of the time, not succeeding at all.

**Comment by juj** [comment]
Oops, the test condition for that function was incorrect. Fixed in the above commit, thanks for noticing!
