### ISSUE TITLE
Not getting same results from Emscripten version as C++ code

### ISSUE THREAD

**Issue by jnmacd** [juj/MathGeoLib#41]
It looks fine at http://clb.demon.fi/minobb/test/ModelView.html.
But I downloaded and compiled latest master and the ConvexHull 
When the following code executes:
<code>

    math::vec* vecarray = new math::vec[uniqueVertex.size()];

    int i=0;

    foreach (const QVector3D& v, uniqueVertex)

    {

        vecarray[i++] = math::vec(v.x(), v.y(), v.z());

    }

    math::OBB ob = math::OBB::OptimalEnclosingOBB(vecarray, uniqueVertex.size());
</code>

I get this error:
Boundary is not connected: there should be edge 33-37 in the boundary!
"false in C:\Users\jason6616\Desktop\dev\MathGeoLib-master\src\Geometry\Polyhedron.cpp:2038"
"Assumption "MATH_NS::IsFinite(m_0c) in C:\Users\jason6616\Desktop\dev\MathGeoLib-master\src\Math\flo"... (unknown length)
"Assumption "MATH_NS::IsFinite(m_1c) in C:\Users\jason6616\Desktop\dev\MathGeoLib-master\src\Math\flo"... (unknown length)
"Assumption "dirArray in C:\Users\jason6616\Desktop\dev\MathGeoLib-master\src\Math\float3x4.cpp:1204""... (unknown length)

Results from online demo:
Convex hull computed in 439.05 msecs, got 40 vertices, 63 faces and 101 edges.
Minimum volume OBB computed in 629.11 msecs. Volume: 0.493*15.711*0.493=3.81337
Minimum volume OBB: Center pos: (309.033, 284.244, 37.335); Diameter: (0.493, 15.711, 0.493)
Local Axes: X:(-0.704, -0.062, 0.707); Y:(-0.087, 0.996, 0.000); Z:(-0.705, -0.062, -0.707) 
Defining corners: c0: (310.064, 276.449, 37.335); cX: (309.717, 276.419, 37.683); cY: (308.695, 292.100, 37.335); cZ: (309.717, 276.419, 36.986)

Some datasets work just fine though...
using MinGW 4.8 on Win 7
Any ideas?

Here is the dataset i am using:

308.1120 292.0490 37.2578
308.1470 292.0520 37.1883
309.5160 276.4010 37.1883
309.4810 276.3980 37.2578
308.2020 292.0570 37.1332
309.5710 276.4060 37.1332
308.2710 292.0630 37.0978
309.6410 276.4120 37.0978
308.3480 292.0690 37.0856
309.7170 276.4190 37.0856
308.4250 292.0760 37.0978
309.7940 276.4260 37.0978
308.4940 292.0820 37.1332
309.8630 276.4320 37.1332
308.5490 292.0870 37.1883
309.9180 276.4370 37.1883
308.5840 292.0900 37.2578
309.9540 276.4400 37.2578
308.5960 292.0910 37.3349
309.9660 276.4410 37.3349
308.5840 292.0900 37.4119
309.9540 276.4400 37.4119
308.5490 292.0870 37.4814
309.9180 276.4370 37.4814
308.4940 292.0820 37.5366
309.8630 276.4320 37.5366
308.4250 292.0760 37.5720
309.7940 276.4260 37.5720
308.3480 292.0690 37.5842
309.7170 276.4190 37.5842
308.2710 292.0630 37.5720
309.6410 276.4120 37.5720
308.2020 292.0570 37.5366
309.5710 276.4060 37.5366
308.1470 292.0520 37.4814
309.5160 276.4010 37.4814
308.1120 292.0490 37.4119
309.4810 276.3980 37.4119
308.1000 292.0480 37.3349
309.4690 276.3970 37.3349
308.3480 292.0690 37.3349
309.7170 276.4190 37.3349

**Comment by juj** [comment]
That message comes from the prerequisite algorithm that computes the convex hull for the input. I've had a lot of trouble with numerical precision in the implementation of the convex hull algorithm I was using, and the best results I got were when I would precenter and scale the input data set so that it is fitted in e.g. a `[-16, 16]` or a `[-128, 128]` axis-aligned cube before computing the convex hull. Try doing such a rescaling step before feeding the data in, i.e. compute the min and max in each direction, and do an uniform scale of the data set and make sure it's centered around zero. Does that help?

**Comment by jnmacd** [comment]
Thank you for your reply.
This might be the case.

I shifted all points and just multiplied by 5, and its producing a result which seems reasonable.

How would I use MathGeoLib to scale these points? I am not sure how to scale properly, so would like to convert my model to a Polyhedron before. But I assume I will run into the same original problem of precision.

Do i directly modify the 'v' and 'f' members to create the object?
Then to scale, would I use Transform(float4x4::UniformScale(5)) ?

**Comment by juj** [comment]
You can try to do something like this (pseudo, might need a bit of tweaking to compile):

    // The input data
    vec *v = /*input array*/;
    const int nPoints = /*size of input*/;

    // Compute the axis-aligned box that encloses the data set
    AABB enclosingAABB = AABB::MinimalEnclosingAABB(v, nPoints);

    // Create a delta offset vector that shifts the box center to the origin. (the  - POINT_VEC_SCALAR(0.f) part is identical to setting .w = 0)
    vec offset = enclosingAABB.CenterPoint() - POINT_VEC_SCALAR(0.f);

    // Compute a uniform scaling factor to scale the data to inside a box of [-128, 128].
    vec boxSize = enclosingAABB.HalfSize();
    float scale = 128.f / Max(boxSize.x, boxSize.y, boxSize.z);

    // Generate scale matrix and its inverse
    float3x4 transform = float3x4::UniformScale(scale) * float3x4::Translate(-offset);
    float3x4 invTransform = transform;
    invTransform.InverseOrthogonalUniformScale();

    // Scale data
    transform.BatchTransformPos(v, nPoints);

    // Compute the convex hull
    Polyhedron cv = Polyhedron::ConvexHull(v, nPoints);

    // Compute minimum OBB
    OBB minOBB = OBB::OptimalEnclosingOBB(cv);

    // Restore convex hull points back to the original coordinate frame
    cv = invTransform * cv;

    // Convert also the computed OBB to the original coordinate frame
    minOBB = invTransform * minOBB;

I've hesitated to make this recentering to occur "under the hood" in convex hull computation, since there's also a chance that it could add numerical imprecision on some other input data that might be very sensitive to it.

**Comment by jnmacd** [comment]
Thanks, its working great on every model I attempt so far.
