### ISSUE TITLE
Triangle - AABB Intersection bug?

### ISSUE THREAD

**Issue by tneukom** [juj/MathGeoLib#51]
```c++
Triangle triangle{ float3{0.0f, 0.0f, 0.0f}, float3{1.0f, 0.0f, 0.0f}, float3{0.0f, 1.0f, 0.0f} };
AABB aabb{ float3{-2.0f, -2.0f, -2.0f}, float3{2.0f, 2.0f, 2.0f} };

bool does_intersect = triangle.Intersects(aabb);
```

The triangle is contained in the AABB but does_intersect is false. It seems to be a problem when the triangle is parallel to the bounding box. I have SSE disabled.

**Comment by juj** [comment]
Thanks! Really good test case, it uncovered a corner case when triangle is perfectly parallel to one of the world axes. Fixed in above commit and added a test.

**Comment by tneukom** [comment]
Awesome, thanks!
