### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by husterlzj** [juj/MathGeoLib#54]
As the title, when to release the new version? I found that the latest version is 2013.

**Comment by juj** [comment]
Releases were made historically as part of coordinating against releases of another project, so we could match "project X released with MathGeoLib version Y". Nowadays MathGeoLib is getting much less development, so there will probably be no new releases anymore, but rather just commits layered into the repository whenever something is changed. I recommend forking and creating a tag or a branch in your fork to signify a release point for your own use, in a good version where things are working well.

Thanks for the question!
