### ISSUE TITLE
bug：aabb capsule intersection, gjk.cpp wrong assert，wrong calculation result

### ISSUE THREAD

**Issue by knowthyselfcn** [juj/MathGeoLib#56]
```c++
  {
        math::vec minPoint = math::vec(1549.69849 , 639.203125 , 1115.08582);
        math::vec maxPoint = math::vec(1554.69849 , 644.203125 ,1120.08582);
        math::AABB aabb(minPoint, maxPoint);

        math::vec a(1072.35388 , 1130.68018, -477.690887);
        math::vec b(1699.54614, 490.913147,1637.29395);

        math::Capsule cylinder(a, b, 4.36077833);

        if (cylinder.Intersects(aabb))
        {
            std::cout << "MathGeoLib intersects\n";
        }
    }

     {
         gte::Vector<3, float> minPoint({ 1549.69849, 639.203125, 1115.08582 });
         gte::Vector<3, float>  maxPoint({ 1554.69849, 644.203125, 1120.08582 });
         gte::AlignedBox3<float>   aabb(minPoint, maxPoint);

         gte::Vector<3, float> a({ 1072.35388, 1130.68018, -477.690887 });
         gte::Vector<3, float> b({ 1699.54614, 490.913147, 1637.29395 });
         gte::Vector<3, float> dir = a - b;    gte::Normalize(dir);
         float height = gte::Length(a - b);

         gte::Line3<float> axis(a, dir);
         gte::Cylinder3<float> cylinder(axis, 4.36077833, height);

         gte::TIQuery<float, gte::AlignedBox3<float>, gte::Cylinder3<float> > query;
         gte::TIQuery<float, gte::AlignedBox3<float>, gte::Cylinder3<float> >::Result res = query(aabb, cylinder);
         if (res.intersect)
         {
             std::cout << "gte intersects\n";
         }

     }
```
Error: Dot(tri023Normal, d01) <= 0.f in MathGeoLib_20190522\src\Algorithm\GJK.cpp:249
terminal output：MathGeoLib intersects。

MathGeoLib： master 20190522， after #55 .

I think this is a bug in GJK algorithm。

uh...  I've checked agian. It seems that GeometricToolsEngine3p25  also gives wrong answer.
If the radius of  gte::Cylinder3<float> cylinder(axis, 4.36077833, height) increases, it still reports no intersection.

**Comment by knowthyselfcn** [comment]
![image](https://user-images.githubusercontent.com/1706836/58221987-2cd7c900-7d47-11e9-8b7b-e1dae7aa93b8.png)

**Comment by knowthyselfcn** [comment]
If I comment out
        1,  MATH_ASSERT_CORRECTNESS  in MathBuildConfig.h
        2, GJK.cpp L248  		//assert(Dot(tri013Normal, d02) <= 0.f);
		                                //assert(Dot(tri023Normal, d01) <= 0.f);
, I got the following error msg.

Error: Assumption ""false && "GJK intersection test did not converge to a result!"", a.SerializeToString(): 1576.98974609375,455.71697998046875,1713.7987060546875,913.54705810546875,1109.4415283203125,-486.113037109375,7.759715557098389, b.SerializeToString(): 1420.60009765625,610.539794921875,1219.4420166015625,1425.60009765625,615.539794921875,1224.4420166015625 in  mathgeolib_20190522\src\geometry\../Algorithm/GJK.h:60" failed! in file  mathgeolib_20190522\src\geometry\../Algorithm/GJK.h, line 60!

**Comment by juj** [comment]
This does look like an issue with single precision floating point limits.

Pushed a commit that pre-translates the objects around a common centered coordinate frame closer to world origin so that more floating point precision is regained. Also adjusted the relevant assertion checks to be computed in double precision as well. With those changes the test passes and reports no collision.
