### ISSUE TITLE
KdTree not working with a single item/multiple items that cannot be split

### ISSUE THREAD

**Issue by merwaaan** [juj/MathGeoLib#57]
Hi,

It seems that MathGeoLib's **KdTree doesn't work when a single object has been added** (also when several objects have been added but they cannot be split into leaves at the root).

This looks like it's due to the `SplitLeaf()` method aborting the building process when it cannot separate objects. When this happens at the root node, it leaves us with a KdTree in an invalid state : the root node is not considered a leaf even though it contains objects and this breaks the queries that will come later due to assertions in DEBUG builds and numerical errors because `splitPos`/`splitAxis` have invalid values.

Minimal reproducible example:

```
// Build the tree

KdTree<Triangle> tree;

Triangle triangle(float3::zero, float3::unitX, float3::unitY);

tree.AddObjects(&triangle, 1);
tree.Build();

// Query

AABB bbox(float3::one * -10, float3::one * 10);

tree.AABBQuery(bbox, [&](KdTree<Triangle>& tree, KdTreeNode& leaf, const AABB& aabb)
{
        auto bucket = tree.Bucket(leaf.bucketIndex);
        auto triangle = tree.Object(*bucket);

         // ... do stuff with triangle ...

         return false;
});
```

A possible fix could be to support this case explicitly in `AABBQuery()` before checking left & right children. Something like this:

```
while(stackSize > 0)
{
	KdTreeNode *cur = stack[--stackSize];
	//assert(!cur->IsLeaf());

        // If the node is a leaf, directly call the callback on it
        if (cur->IsLeaf())
        {
            leafCallback(*this, *cur, aabb);
            return;
        }

        // Deal with with children normally

        ...
}
```

I might even be better to deal with this case in `Build()` but I'm not familiar enough with the class to be sure which strategy is best.

Any thoughts about this?
Should I propose a PR?

**Comment by juj** [comment]
Thanks for the detailed analysis and a full test case! Should be fixed by the above commit, hopefully it will also cover the more complex scenarios where the root cannot be split.

**Comment by merwaaan** [comment]
Thanks for the quick fix!
