### ISSUE TITLE
Unexpected results with Polyhedron::Triangulate()

### ISSUE THREAD

**Issue by merwaaan** [juj/MathGeoLib#60]
Hi,

When tesselating a polyhedron with a single concave face, I sometimes get unexpected results, like in the following screenshot:

![mglbug](https://user-images.githubusercontent.com/243841/81051325-d0bb7580-8ec1-11ea-98b8-142993661b04.JPG)

(I was under the impression that MathGeoLib's supports producing triangles from concave polygons but I haven't been able to find any formal confirmation in the code or the documentation, so please correct me if I'm wrong about this!)

Any idea?
Thanks.

**Comment by juj** [comment]
Unfortunately the triangulation function is only for convex polyhedrons/polygons, there is currently no triangulation support for concave polyhedrons/polygons. Adjusted the API naming to be clear about this (and to make room for a more generic algorithm if one might exist some day)

**Comment by merwaaan** [comment]
Thanks for the clarification.
I was misled by the fact the algorithm actually works for _some_ concave shapes!
