### ISSUE TITLE
Forward-declared float2x2 & float2x3 do not exist

### ISSUE THREAD

**Issue by merwaaan** [juj/MathGeoLib#64]
Hi,

Not a critical issue but I just got bit because I wrote some code using the float2x2 matrix type that MGL forward-declares but it seems that it does not actually exist :)

(Same thing for float 2x3)

Cheers.

**Comment by juj** [comment]
Oh lol, not sure what that was about :)

**Comment by juj** [comment]
Fixed in https://github.com/juj/MathGeoLib/commit/b096dc3e8531c20896a43c0b48c0662923fcd1f3
