### ISSUE TITLE
Missing Feature in Quadtree?

### ISSUE THREAD

**Issue by ddiakopoulos** [juj/MathGeoLib#67]
Hi - thanks for your time developing this library. I've noticed you wrote a robust Quadtree class. I'd like to use it but I need the nearest neighbor function which is hidden behind a `MATH_CONTAINERLIB_SUPPORT` macro, which _i think_ only requires `MaxHeap`. Would this be something you would consider publicly adding to the library?

**Comment by juj** [comment]
I would publicize it if I could, but unfortunately it is not my decision :(

Maybe the better path forward would be to add a backing that uses STL `std::priority_queue` instead of `MaxHeap`. They are essentially the same API. If you are able to provide a PR, I'd be happy to merge that in.

**Comment by ddiakopoulos** [comment]
Thanks for the quick reply! I'll make a PR if I find time :)
